# Generated by Django 3.2.16 on 2024-04-28 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0002_holiday_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holiday',
            options={'verbose_name': 'Праздник', 'verbose_name_plural': 'Праздники'},
        ),
    ]
