# Generated by Django 3.2.16 on 2024-05-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0003_alter_holiday_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='holiday',
            constraint=models.UniqueConstraint(fields=('user', 'date', 'name'), name='unique_holidays'),
        ),
    ]
