# Generated by Django 3.2.16 on 2024-04-28 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gifts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gift',
            options={'verbose_name': 'Подарок', 'verbose_name_plural': 'Подарки'},
        ),
        migrations.AddField(
            model_name='gift',
            name='is_donated',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gift',
            name='is_want',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gift',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gift',
            name='link',
            field=models.TextField(verbose_name='Ссылка на пример подарка'),
        ),
    ]
