# Generated by Django 3.2.16 on 2024-05-16 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0004_holiday_unique_holidays'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gifts', '0003_auto_20240502_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holidays.holiday', verbose_name='Что празднует'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='is_donated',
            field=models.BooleanField(default=False, verbose_name='Уже подарен'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
