# Generated by Django 3.2.16 on 2024-05-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_subscribe_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Адрес для почтовых отправлений пользователю'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_open',
            field=models.BooleanField(default=False, verbose_name='Желание получать анонимный подарок'),
        ),
        migrations.AddField(
            model_name='subscribe',
            name='is_congratulate',
            field=models.BooleanField(default=True, verbose_name='Поздравлять ли пользователя'),
        ),
        migrations.AddField(
            model_name='subscribe',
            name='name',
            field=models.CharField(default='Никак', max_length=50, verbose_name='Как называет пользователя'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='subscribe',
            constraint=models.UniqueConstraint(fields=('user', 'subscribe'), name='unique_subscriptions'),
        ),
    ]
